G/Client/UI/G.Client.UI.Admin/Controllers/DeployServerManageController.cs
using G.Client.UI.Admin.Business;
using G.Client.UI.Admin.Models.DeployManageModels.DeployServerModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace G.Client.UI.Admin.Controllers
{
    [Authorize]
    public class DeployServerManageController : Controller
    {
        // GET: DeployManage
        public async Task<ActionResult> Index()
        {
            var deployServerList = await new DeployServerBusiness().GetList();

            return View(deployServerList);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateDeployServerViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View();
            }

            var id = await new DeployServerBusiness().Create(model);

            return View();
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = await new DeployServerBusiness().FindByID(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditDeployServerViewModel model)
        {
            ViewBag.IsPostBack = true;

            if (!ModelState.IsValid)
            {
                return View();
            }

            await new DeployServerBusiness().Update(model);

            return View(model);
        }
    }
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServerManage/Create.cshtml
@{
    ViewBag.Title = "创建部署服务器";
    bool isFirstRadio = true;
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

@section css{
    <!--iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/plugins/iCheck/all.css">
}

@section js{
    <!-- iCheck 1.0.1 -->
    <script src="~/theme/AdminLTE-2.3.11/plugins/iCheck/icheck.min.js"></script>
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Create", "DeployServerManage", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <input class="form-control" type="text" id="Name" name="Name" placeholder="服务器名"><br>
            <input class="form-control" type="text" id="ServerIdentity" name="ServerIdentity" placeholder="服务器标识"><br>
            <input class="form-control" type="text" id="IPAddress" name="IPAddress" placeholder="IP地址"><br>
            <div class="form-group">
                <div class="col-lg-pull-1" style="margin-left:20px">
                    状态：
                    @foreach (var item in Enum.GetNames(typeof(G.Client.UI.Admin.Views.Enums.DeployServerStatus)))
                    {
                        var deployServerStatus = (G.Client.UI.Admin.Views.Enums.DeployServerStatus)Enum.Parse(typeof(G.Client.UI.Admin.Views.Enums.DeployServerStatus), item);
                        var checkedSign = isFirstRadio ? "checked" : "";
                        isFirstRadio = false;
                        var value = (int)deployServerStatus;
                        <label>
                            <input type="radio" id="Status" value="@value" name="Status" class="minimal" @checkedSign>@deployServerStatus.ToString() &nbsp;&nbsp;
                        </label>
                    }
                </div>
            </div>
        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
    <form class="form-horizontal"></form>
</div>

@section initJS{
    <script>
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServerManage/Edit.cshtml
@model G.Client.UI.Admin.Models.DeployManageModels.DeployServerModels.EditDeployServerViewModel
@{
    ViewBag.Title = "编辑部署服务器";
    var allError = ViewData.ModelState.Where(ms => ms.Value.Errors.Count > 0).SelectMany(ms => ms.Value.Errors);
}

@section css{
    <!--iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/plugins/iCheck/all.css">
}

@section js{
    <!-- iCheck 1.0.1 -->
    <script src="~/theme/AdminLTE-2.3.11/plugins/iCheck/icheck.min.js"></script>
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    @using (Html.BeginForm("Edit", "DeployServerManage", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken();
        <div class="box-body">

            @if (allError.Count() > 0)
            {
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-ban"></i> 错误！</h4>
                    @foreach (var error in allError)
                    {
                        @error.ErrorMessage
                        <br />
                    }
                </div>
            }
            else if (ViewBag.IsPostBack != null && ViewBag.IsPostBack)
            {
                <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> 成功！</h4>
                </div>
            }

            <input class="form-control" type="text" id="Name" name="Name" placeholder="服务器名" value="@Model.Name"><br>
            <input class="form-control" type="text" id="ServerIdentity" name="ServerIdentity" placeholder="服务器标识" value="@Model.ServerIdentity"><br>
            <input class="form-control" type="text" id="IPAddress" name="IPAddress" placeholder="IP地址" value="@Model.IPAddress"><br>
            <div class="form-group">
                <div class="col-lg-pull-1" style="margin-left:20px">
                    状态：
                    @foreach (var item in Enum.GetNames(typeof(G.Client.UI.Admin.Views.Enums.DeployServerStatus)))
                    {
                        var deployServerStatus = (G.Client.UI.Admin.Views.Enums.DeployServerStatus)Enum.Parse(typeof(G.Client.UI.Admin.Views.Enums.DeployServerStatus), item);
                        var checkedSign = deployServerStatus == Model.Status ? "checked" : "";
                        var value = (int)deployServerStatus;
                        <label>
                            <input type="radio" id="Status" value="@value" name="Status" class="minimal" @checkedSign>@deployServerStatus.ToString() &nbsp;&nbsp;
                        </label>
                    }
                </div>
            </div>
        </div>
    <!-- /.box-body -->
        <div class="box-footer bg-gray-light">
            <button type="submit" class="btn btn-primary pull-right">保存</button>
        </div>
    <!-- /.box-footer -->
    }
    <form class="form-horizontal"></form>
</div>

@section initJS{
    <script>
        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
        });
    </script>
}

G/Client/UI/G.Client.UI.Admin/Views/DeployServerManage/Index.cshtml
@model List<G.Client.UI.Admin.Models.DeployManageModels.DeployServerModels.DeployServerViewModel>
@{
    ViewBag.Title = "部署服务器管理";
}

@section css{
    <link rel="stylesheet" href="~/theme/AdminLTE-2.3.11/extended/ResponsiveTable.css">
}

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">@ViewBag.Title</h3>
        <div class="box-tools">
            <div class="input-group input-group-sm">
                <a class="btn btn-block btn-primary btn-sm" href="~/DeployServerManage/Create">新建</a>
            </div>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th style="width: 30px">#</th>
                    <th>服务器名</th>
                    <th>服务器标识</th>
                    <th>IP地址</th>
                    <th>状态</th>
                    <th>最后修改人</th>
                    <th>最后修改时间</th>
                    <th style="width: 50px">操作</th>
                </tr>
                @if (Model.Count == 0)
                {
                    <tr class="text-center text-gray"><td colspan="8"><span style="font-size:30px"><i class="fa fa-warning"></i>&nbsp;没有数据</span></td></tr>
                }
                else
                {
                    for (int i = 0; i < Model.Count; i++)
                    {
                        var server = Model[i];
                        <tr>
                            <td style="vertical-align:middle">@(i + 1).</td>
                            <td style="vertical-align:middle;">@server.Name</td>
                            <td style="vertical-align:middle">@server.ServerIdentity</td>
                            <td style="vertical-align:middle">@server.IPAddress</td>
                            <td style="vertical-align:middle">
                                @switch (server.Status)
                                {
                                    case G.Client.UI.Admin.Views.Enums.DeployServerStatus.Online:
                                        <span class="label label-success">@server.Status</span>
                                        break;
                                    case G.Client.UI.Admin.Views.Enums.DeployServerStatus.Offline:
                                        <span class="label label-danger">@server.Status</span>
                                        break;
                                    default:
                                        break;
                                }
                            </td>
                            <td style="vertical-align:middle">@server.UpdateUserName</td>
                            <td style="vertical-align:middle">@server.UpdateTime</td>
                            <td style="vertical-align:middle">
                                <a class="btn btn-social-icon" style="height:31px" href="~/DeployServerManage/Edit/@server.ID"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>